spring:
  datasource:
    url: jdbc:h2:file:~/studentspringboot
    username: sa
    password: 
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.kgisl.studentspringboot: INFO
  
  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: logs/studentspringboot.log      